"""Asynchronous Python client for Mealie."""

from aiomealie.exceptions import (
    MealieConnectionError,
    MealieError,
    MealieAuthenticationError,
    MealieValidationError,
    MealieBadRequestError,
    MealieNotFoundError,
)
from aiomealie.mealie import MealieClient
from aiomealie.models import (
    About,
    CategoriesResponse,
    StartupInfo,
    GroupSummary,
    Theme,
    BaseRecipe,
    RecipesResponse,
    TagsResponse,
    Tool,
    ToolsResponse,
    Mealplan,
    MealplanResponse,
    MealplanEntryType,
    MutateShoppingItem,
    ShoppingList,
    ShoppingListsResponse,
    ShoppingItem,
    ShoppingItemsResponse,
    UserInfo,
    Recipe,
    Instruction,
    Ingredient,
    Tag,
    Statistics,
)

__all__ = [
    "About",
    "CategoriesResponse",
    "MealieConnectionError",
    "MealieError",
    "MealieAuthenticationError",
    "MealieBadRequestError",
    "MealieNotFoundError",
    "MealieValidationError",
    "MealieClient",
    "StartupInfo",
    "GroupSummary",
    "Theme",
    "BaseRecipe",
    "Recipe",
    "Instruction",
    "Ingredient",
    "Tag",
    "TagsResponse",
    "Tool",
    "ToolsResponse",
    "RecipesResponse",
    "Mealplan",
    "MealplanResponse",
    "MealplanEntryType",
    "ShoppingItem",
    "Statistics",
    "MutateShoppingItem",
    "ShoppingItemsResponse",
    "ShoppingList",
    "ShoppingListsResponse",
    "UserInfo",
]
